"""Implement association object for recipe ingredients

Revision ID: ec36920706f6
Revises: 3d9cc7ef2646
Create Date: 2025-09-02 22:33:34.863906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec36920706f6'
down_revision: Union[str, Sequence[str], None] = '3d9cc7ef2646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'title',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
