"""Add owner_id to recipes table

Revision ID: f494a9ce9c31
Revises: 08423304e774
Create Date: 2025-09-01 21:33:38.539631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f494a9ce9c31'
down_revision: Union[str, Sequence[str], None] = '08423304e774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_constraint(op.f('recipes_user_id_fkey'), 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['owner_id'], ['id'])
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_user_id_fkey'), 'recipes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('recipes', 'owner_id')
    # ### end Alembic commands ###
